version: 2
updates:
  - package-ecosystem: "github-actions"
    target-branch: trunk
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
    labels:
      - "domain/product-ops"
    groups:
      all:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    target-branch: 6.6.x
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(deps): "
    labels:
      - "domain/product-ops"
    groups:
      all:
        patterns:
          - "*"
