# Add f.e. 'Extension:B2B-Suite' label if issue contains the word / regex 'Extension:B2B-Suite'
version: 1
appendOnly: true #only add labels never remove them automatically
labels:
    - label: "Platform(Default)"
      body: 'Platform\(Default\)'
    - label: "extension/Commercial"
      body: "Extension:Commercial"
    - label: "extension/B2B-Suite"
      body: "Extension:B2B-Suite"
    - label: "extension/CMS-Extensions"
      body: "Extension:CMS-Extensions"
    - label: "extension/Custom-Products"
      body: "Extension:Custom-Products"
    - label: "extension/Dynamic-Access"
      body: "Extension:Dynamic-Access"
    - label: "extension/Language-Pack"
      body: "Extension:Language-Pack"
    - label: "extension/Migration-Assistant"
      body: "Extension:Migration-Assistant"
    - label: "extension/PayPal-Integration"
      body: "Extension:PayPal-Integration"
    - label: "extension/Publisher"
      body: "Extension:Publisher"
    - label: "extension/Sales-Agent"
      body: "Extension:Sales-Agent"
    - label: "extension/Recommendations"
      body: "Extension:Recommendations"
    - label: "extension/Social-Shopping"
      body: "Extension:Social-Shopping"
