name: Bug report 🐛
description: Errors or flaws in the code are leading to incorrect or unexpected behavior.
type: Bug
body:
    - type: markdown
      attributes:
          value: |
              Thanks for taking the time to fill out this bug report!
    - type: input
      id: shopware-version
      attributes:
          label: Shopware Version
          description: Please specify your Shopware version (e.g. 6.4.20.0). If you're using Shopware Cloud, simply type "cloud".
      validations:
          required: true
    - type: dropdown
      id: extension
      attributes:
          label: Affected area / extension
          description: In which area or extension of the product does the behavior occur?
          options:
              - Platform(Default)
              - Extension:Commercial
              - Extension:B2B-Suite
              - Extension:CMS-Extensions
              - Extension:Custom-Products
              - Extension:Digital-Sales-Room
              - Extension:Dynamic-Access
              - Extension:Language-Pack
              - Extension:Migration-Tool
              - Extension:PayPal-Integration
              - Extension:Publisher
              - Extension:Sales-Agent
              - Extension:Recommendations
              - Extension:Social-Shopping
              - Extension:3D-Preview-Generator
              - Extension:Image-Editor
              - Extension:Copilot
      validations:
          required: true
    - type: textarea
      id: actual-behaviour
      attributes:
          label: Actual behaviour
          description: Please describe the issue
      validations:
          required: true
    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour
          description: What did you expect to happen?
      validations:
          required: true
    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: How to reproduce
          description: Tell us how the bug can be reproduced
      validations:
          required: true