name: Add needs-triage label to new PullRequests and Issues

on:
  pull_request_target:
    types: [opened]
  issues:
    types: [opened]

jobs:
  label:
    runs-on: ubuntu-24.04
    steps:
      - uses: srvaroa/labeler@0a20eccb8c94a1ee0bed5f16859aece1c45c3e55 # 1.13.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          config_path: .github/labeler-needs-triage.yml
