name: Deploy

on:
  push:
    branches:
      - trunk

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read

jobs:
  release-schedule:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4
        with:
          fetch-depth: 2

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@0d04879d366c9959065c153479c620d35e5c4097 # 3
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/UploadReleaseCalendar
          role-session-name: github-actions
          aws-region: eu-central-1

      - name: Setup PHP
        uses: shivammathur/setup-php@6c489b2fc701c5f9ed70ccebe221b567bee578c0 # 2
        with:
          php-version: 8.3

      - name: Publish release schedule
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release download --repo shopware/release-schedule --pattern 'release-schedule.phar'
          php release-schedule.phar publish
