name: Backport

on:
  pull_request_target:
    types:
      - closed
      - labeled

permissions:
  id-token: write

jobs:
  backport:
    runs-on: ubuntu-24.04
    if: >
      github.event.pull_request.merged
      && (
        github.event.action == 'closed'
          && contains(join(github.event.pull_request.labels.*.name, ','), 'backport-')
        || (
          github.event.action == 'labeled'
          && contains(github.event.label.name, 'backport-')
        )
      )
    steps:
      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # 1.0.0
        id: sts-shopware-backport
        with:
          scope: shopware
          identity: ShopwareBackport
      - name: Backporting
        uses: kiegroup/git-backporting@main
        with:
          auth: ${{ steps.sts-shopware-backport.outputs.token }}
          target-branch-pattern: "^backport-(?<target>([^ ]+))$"
          pull-request: ${{ github.event.pull_request.url }}
