name: Sync Repo

on:
  push:
    branches:
      - trunk
      - 6.[0-9]*.x
      - 6.[0-9]*.[0-9]*.x
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # 4
        with:
          fetch-depth: 0

      - uses: octo-sts/action@a26b0c6455c7f13316f29a8766287f939e75f6c8 # 1.0.2
        id: sts-shopware-private
        with:
          scope: shopware
          identity: ShopwarePrivateSync

      - name: Push to private fork
        run: |
          git config --unset http."https://github.com/".extraheader
          git config "http.https://github.com/shopware/shopware-private.git/.extraheader" "AUTHORIZATION: basic $(echo -n "x-access-token:${{ steps.sts-shopware-private.outputs.token }}" | base64)"
          git remote add private https://github.com/shopware/shopware-private.git
          git fetch private
          git push -f private ${{ github.ref }}

