name: Sync Repo

on:
  push:
    branches:
      - trunk
      - 6.5.x
      - 6.6.x
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-24.04
    if: github.repository == 'shopware/shopware'
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4
        with:
          fetch-depth: 0

      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # 1.0.0
        id: sts-shopware-private
        with:
          scope: shopware
          identity: ShopwarePrivateSync

      - name: Push to private fork
        run: |
          git config --unset http."https://github.com/".extraheader
          git config "http.https://github.com/shopware/shopware-private.git/.extraheader" "AUTHORIZATION: basic $(echo -n "x-access-token:${{ steps.sts-shopware-private.outputs.token }}" | base64)"
          git remote add private https://github.com/shopware/shopware-private.git
          git fetch private
          git push -f private ${{ github.ref }}

