name: Visual Tests

permissions:
  id-token: write

# Once proven stable, this workflow can be integrated into the integration workflow
# by adding "Visual" to the "name" matrix element.
on:
  workflow_dispatch:
    inputs:
      update-snapshots:
        description: 'Update snapshots?'
        type: boolean
        default: false
      currents:
        description: 'Report to currents?'
        type: boolean
        default: false
      filter:
        description: 'Use this field to provide a filter that will be passed to playwrights `--grep` input.'
        type: string
        default: ''

  workflow_call:
    inputs:
      update-snapshots:
        description: 'Update snapshots?'
        type: boolean
        default: false
      currents:
        description: 'Report to currents?'
        type: boolean
        default: false
      filter:
        description: 'Use this field to provide a filter that will be passed to playwrights `--grep` input.'
        type: string
        default: ''

jobs:
  visual-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: ./.github/actions/ats
        with:
          project: 'Visual'
          install: 'true'
          workers: 1
          extra-options: >-
            ${{ inputs.update-snapshots && ' --update-snapshots' || '' }}
            ${{ inputs.filter && format(' --grep="{0}"', inputs.filter) || '' }}
          use-currents: ${{ inputs.currents && 'true' || '' }}
          currents-project-id: ${{ secrets.CURRENTS_PROJECT_ID_VISUAL }}
          currents-record-key: ${{ secrets.CURRENTS_RECORD_KEY }}
        continue-on-error: true
